"""
Unit tests for `src.codegen`.

Goals:
  1. Generated scripts must embed the data-snapshot timestamp so a
     downstream reader can pin the analysis to a known vintage.
  2. Python and R fetch logic must stay in sync (same full-series fetch
     + client-side filter pattern — no server-side `end =` mismatch).
  3. Every (chart_type × flavour) combination must produce syntactically
     plausible output with the expected library imports.
"""

from __future__ import annotations

from datetime import datetime, timezone

import pytest

from src.codegen import python_code, quarto_code, r_code

# ── Fixtures ──────────────────────────────────────────────────────────────────

_WDI_IND = {
    "id": "under5_mortality",
    "name": "Under-5 Mortality Rate",
    "indicator": "SH.DYN.MORT",
    "source": "wdi",
    "unit": "deaths per 1000",
}

_OWID_IND = {
    "id": "extreme_poverty",
    "name": "Extreme Poverty",
    "slug": "share-of-population-in-extreme-poverty",
    "source": "owid",
    "unit": "% of population",
}

_SNAPSHOT = datetime(2026, 4, 18, 10, 30, tzinfo=timezone.utc)


def _common_kwargs() -> dict:
    return dict(
        selected_countries=["France", "Nigeria", "India"],
        year_range=(2000, 2020),
        map_year=2020,
        bar_year=2020,
        top_n=15,
        log_scale=False,
        color_scale="Viridis",
        chart_title="Test chart",
        snapshot=_SNAPSHOT,
    )


# ── Python ────────────────────────────────────────────────────────────────────

@pytest.mark.parametrize("chart", ["World Map", "Line Chart", "Bar Chart"])
def test_python_embeds_snapshot(chart):
    code = python_code(_WDI_IND, chart_type=chart, **_common_kwargs())
    assert "2026-04-18" in code
    assert "Generated by EasyViz" in code


def test_python_wdi_uses_value_api():
    code = python_code(_WDI_IND, chart_type="World Map", **_common_kwargs())
    assert "api.worldbank.org" in code
    assert "SH.DYN.MORT" in code
    # No server-side year filter in URL — must fetch full series.
    assert "date=1960:2030" in code


def test_python_owid_uses_grapher_csv():
    code = python_code(_OWID_IND, chart_type="Line Chart", **_common_kwargs())
    assert "ourworldindata.org/grapher" in code
    assert "share-of-population-in-extreme-poverty" in code


def test_python_line_chart_preserves_gaps():
    code = python_code(_WDI_IND, chart_type="Line Chart", **_common_kwargs())
    # connectgaps=False is a reproducibility-correctness guarantee
    assert "connectgaps=False" in code


def test_python_log_scale_injects_log1p():
    code = python_code(
        _WDI_IND, chart_type="Line Chart",
        **{**_common_kwargs(), "log_scale": True},
    )
    assert "log1p" in code


def test_python_has_reproducibility_footer():
    code = python_code(_WDI_IND, chart_type="World Map", **_common_kwargs())
    assert "pip freeze" in code


# ── R ─────────────────────────────────────────────────────────────────────────

@pytest.mark.parametrize("flavour", ["plotly", "ggplot2"])
@pytest.mark.parametrize("chart", ["World Map", "Line Chart", "Bar Chart"])
def test_r_embeds_snapshot(chart, flavour):
    code = r_code(_WDI_IND, chart_type=chart, flavour=flavour, **_common_kwargs())
    assert "2026-04-18" in code
    assert "sessionInfo()" in code  # every R script ends with sessionInfo


def test_r_wdi_fetch_matches_python_semantics():
    """
    Python fetches the full series and filters client-side; R must do
    the same. The previous R codegen used `end = user_year`, causing
    the two scripts to yield different samples. This test guards
    against regression.
    """
    code = r_code(_WDI_IND, chart_type="World Map", **_common_kwargs())
    import re
    assert re.search(r"end\s*=\s*2030", code), "R code must fetch full range and filter client-side"
    assert re.search(r"start\s*=\s*1960", code)
    # The user-facing filter must happen AFTER fetch, via tidyverse.
    assert "filter(" in code
    assert "%in% countries" in code


def test_r_ggplot_uses_rnaturalearth_for_map():
    code = r_code(
        _WDI_IND, chart_type="World Map", flavour="ggplot2", **_common_kwargs()
    )
    assert "rnaturalearth" in code
    assert "geom_sf" in code


def test_r_plotly_uses_plot_geo_for_map():
    code = r_code(
        _WDI_IND, chart_type="World Map", flavour="plotly", **_common_kwargs()
    )
    assert "plot_geo" in code


def test_r_ggplot_line_has_geom_line():
    code = r_code(
        _WDI_IND, chart_type="Line Chart", flavour="ggplot2", **_common_kwargs()
    )
    assert "geom_line" in code


def test_r_owid_uses_read_csv():
    code = r_code(_OWID_IND, chart_type="Line Chart", flavour="ggplot2", **_common_kwargs())
    assert "read_csv" in code
    assert "share-of-population-in-extreme-poverty" in code


# ── Quarto ────────────────────────────────────────────────────────────────────

def test_quarto_yaml_header_and_fenced_r_block():
    qmd = quarto_code(_WDI_IND, chart_type="World Map", **_common_kwargs())
    assert qmd.startswith("---")
    assert "format:" in qmd
    assert "```{r}" in qmd
    # Ends with a closing fence.
    assert qmd.rstrip().endswith("```")


def test_quarto_embeds_indicator_name_and_snapshot():
    qmd = quarto_code(_WDI_IND, chart_type="Line Chart", **_common_kwargs())
    assert "Under-5 Mortality Rate" in qmd
    assert "2026-04-18" in qmd


def test_quarto_defaults_to_ggplot_flavour():
    qmd = quarto_code(_WDI_IND, chart_type="Bar Chart", **_common_kwargs())
    # Default flavour is ggplot2 → rnaturalearth won't appear for bar charts
    # but geom_col or geom_line should.
    assert "library(ggplot2)" in qmd or "ggplot(" in qmd


# ── Title escaping ────────────────────────────────────────────────────────────

def test_title_quotes_are_escaped_in_python():
    kwargs = {**_common_kwargs(), "chart_title": 'GDP "per capita"'}
    code = python_code(_WDI_IND, chart_type="Line Chart", **kwargs)
    # The raw unescaped quote would break the generated Python string literal.
    assert 'GDP \\"per capita\\"' in code


def test_title_quotes_are_escaped_in_r():
    kwargs = {**_common_kwargs(), "chart_title": 'GDP "per capita"'}
    code = r_code(_WDI_IND, chart_type="Line Chart", flavour="ggplot2", **kwargs)
    assert 'GDP \\"per capita\\"' in code
