"""
Curated catalog of development indicators from OWID and World Bank (WDI).
Each entry defines source, fetch parameters, unit, and search tags.
"""

INDICATORS = [
    # ── HEALTH ────────────────────────────────────────────────────────────────
    {
        "id": "under5_mortality",
        "name": "Under-5 Mortality Rate",
        "category": "Health",
        "source": "wdi",
        "indicator": "SH.DYN.MORT",
        "unit": "deaths per 1,000 live births",
        "tags": ["health", "mortality", "children", "death", "child", "under 5"],
    },
    {
        "id": "life_expectancy",
        "name": "Life Expectancy at Birth",
        "category": "Health",
        "source": "wdi",
        "indicator": "SP.DYN.LE00.IN",
        "unit": "years",
        "tags": ["health", "life", "expectancy", "longevity", "age"],
    },
    {
        "id": "maternal_mortality",
        "name": "Maternal Mortality Ratio",
        "category": "Health",
        "source": "wdi",
        "indicator": "SH.STA.MMRT",
        "unit": "deaths per 100,000 live births",
        "tags": ["health", "maternal", "women", "mortality", "birth", "mothers"],
    },
    {
        "id": "infant_mortality",
        "name": "Infant Mortality Rate",
        "category": "Health",
        "source": "wdi",
        "indicator": "SP.DYN.IMRT.IN",
        "unit": "per 1,000 live births",
        "tags": ["health", "infant", "mortality", "baby", "child", "neonatal"],
    },
    {
        "id": "health_expenditure",
        "name": "Health Expenditure (% of GDP)",
        "category": "Health",
        "source": "wdi",
        "indicator": "SH.XPD.CHEX.GD.ZS",
        "unit": "% of GDP",
        "tags": ["health", "spending", "expenditure", "gdp", "budget"],
    },
    {
        "id": "malnutrition",
        "name": "Malnutrition Prevalence (children under 5)",
        "category": "Health",
        "source": "wdi",
        "indicator": "SH.STA.MALN.ZS",
        "unit": "% of children under 5",
        "tags": ["malnutrition", "nutrition", "hunger", "food", "children", "wasting"],
    },
    # ── ECONOMY ───────────────────────────────────────────────────────────────
    {
        "id": "gdp_per_capita_ppp",
        "name": "GDP per Capita, PPP (constant 2017 USD)",
        "category": "Economy",
        "source": "wdi",
        "indicator": "NY.GDP.PCAP.PP.KD",
        "unit": "constant 2017 USD",
        "tags": ["economy", "gdp", "income", "wealth", "ppp", "purchasing power"],
    },
    {
        "id": "gdp_growth",
        "name": "GDP Growth Rate",
        "category": "Economy",
        "source": "wdi",
        "indicator": "NY.GDP.MKTP.KD.ZG",
        "unit": "% per year",
        "tags": ["economy", "gdp", "growth", "rate", "recession"],
    },
    {
        "id": "extreme_poverty",
        "name": "Extreme Poverty Rate ($2.15/day)",
        "category": "Economy",
        "source": "wdi",
        "indicator": "SI.POV.DDAY",
        "unit": "% of population",
        "tags": ["poverty", "extreme poverty", "income", "poor", "2.15", "dollar"],
    },
    {
        "id": "inflation",
        "name": "Inflation, Consumer Prices",
        "category": "Economy",
        "source": "wdi",
        "indicator": "FP.CPI.TOTL.ZG",
        "unit": "% per year",
        "tags": ["inflation", "prices", "cpi", "monetary", "economy"],
    },
    {
        "id": "unemployment",
        "name": "Unemployment Rate",
        "category": "Economy",
        "source": "wdi",
        "indicator": "SL.UEM.TOTL.ZS",
        "unit": "% of labor force",
        "tags": ["unemployment", "jobs", "labor", "work", "employment"],
    },
    {
        "id": "fdi",
        "name": "FDI Net Inflows (% of GDP)",
        "category": "Economy",
        "source": "wdi",
        "indicator": "BX.KLT.DINV.WD.GD.ZS",
        "unit": "% of GDP",
        "tags": ["fdi", "foreign direct investment", "investment", "trade", "capital"],
    },
    {
        "id": "oda",
        "name": "Net ODA Received (% of GNI)",
        "category": "Economy",
        "source": "wdi",
        "indicator": "DT.ODA.ODAT.GN.ZS",
        "unit": "% of GNI",
        "tags": ["oda", "aid", "development aid", "official development assistance", "donor"],
    },
    {
        "id": "govt_debt",
        "name": "Government Debt (% of GDP)",
        "category": "Economy",
        "source": "wdi",
        "indicator": "GC.DOD.TOTL.GD.ZS",
        "unit": "% of GDP",
        "tags": ["debt", "government", "fiscal", "budget", "gdp", "deficit"],
    },
    # ── EDUCATION ─────────────────────────────────────────────────────────────
    {
        "id": "literacy_rate",
        "name": "Adult Literacy Rate",
        "category": "Education",
        "source": "wdi",
        "indicator": "SE.ADT.LITR.ZS",
        "unit": "% of adults (15+)",
        "tags": ["education", "literacy", "reading", "writing", "adults", "school"],
    },
    {
        "id": "school_enrollment_primary",
        "name": "Primary School Enrollment",
        "category": "Education",
        "source": "wdi",
        "indicator": "SE.PRM.ENRR",
        "unit": "% gross",
        "tags": ["education", "school", "enrollment", "primary", "children"],
    },
    {
        "id": "school_enrollment_secondary",
        "name": "Secondary School Enrollment",
        "category": "Education",
        "source": "wdi",
        "indicator": "SE.SEC.ENRR",
        "unit": "% gross",
        "tags": ["education", "school", "enrollment", "secondary"],
    },
    {
        "id": "edu_expenditure",
        "name": "Education Expenditure (% of GDP)",
        "category": "Education",
        "source": "wdi",
        "indicator": "SE.XPD.TOTL.GD.ZS",
        "unit": "% of GDP",
        "tags": ["education", "spending", "expenditure", "gdp", "budget"],
    },
    # ── ENVIRONMENT ───────────────────────────────────────────────────────────
    {
        "id": "co2_per_capita",
        "name": "CO₂ Emissions per Capita",
        "category": "Environment",
        "source": "wdi",
        "indicator": "EN.GHG.CO2.PC.CE.AR5",
        "unit": "metric tons per capita",
        "tags": ["co2", "carbon", "emissions", "climate", "environment", "pollution", "ghg"],
    },
    {
        "id": "forest_area",
        "name": "Forest Area (% of Land)",
        "category": "Environment",
        "source": "wdi",
        "indicator": "AG.LND.FRST.ZS",
        "unit": "% of land area",
        "tags": ["forest", "trees", "land", "environment", "deforestation", "nature"],
    },
    {
        "id": "access_electricity",
        "name": "Access to Electricity",
        "category": "Environment",
        "source": "wdi",
        "indicator": "EG.ELC.ACCS.ZS",
        "unit": "% of population",
        "tags": ["electricity", "energy", "access", "infrastructure", "power"],
    },
    {
        "id": "renewable_energy",
        "name": "Renewable Energy Share",
        "category": "Environment",
        "source": "wdi",
        "indicator": "EG.FEC.RNEW.ZS",
        "unit": "% of total final energy",
        "tags": ["renewable", "energy", "solar", "wind", "environment", "climate", "clean"],
    },
    # ── DEMOGRAPHICS ──────────────────────────────────────────────────────────
    {
        "id": "population",
        "name": "Total Population",
        "category": "Demographics",
        "source": "wdi",
        "indicator": "SP.POP.TOTL",
        "unit": "number of people",
        "tags": ["population", "people", "demographics", "size", "headcount"],
    },
    {
        "id": "fertility_rate",
        "name": "Total Fertility Rate",
        "category": "Demographics",
        "source": "wdi",
        "indicator": "SP.DYN.TFRT.IN",
        "unit": "births per woman",
        "tags": ["fertility", "birth rate", "children", "demographics", "reproduction"],
    },
    {
        "id": "urban_population",
        "name": "Urban Population Share",
        "category": "Demographics",
        "source": "wdi",
        "indicator": "SP.URB.TOTL.IN.ZS",
        "unit": "% of total population",
        "tags": ["urban", "city", "urbanization", "demographics", "rural"],
    },
    # ── GOVERNANCE ────────────────────────────────────────────────────────────
    {
        "id": "women_parliament",
        "name": "Women in Parliament",
        "category": "Governance",
        "source": "wdi",
        "indicator": "SG.GEN.PARL.ZS",
        "unit": "% of parliamentary seats",
        "tags": ["women", "parliament", "gender", "politics", "governance", "representation"],
    },
    {
        "id": "access_water",
        "name": "Access to Safe Drinking Water",
        "category": "Health",
        "source": "wdi",
        "indicator": "SH.H2O.SMDW.ZS",
        "unit": "% of population",
        "tags": ["water", "sanitation", "access", "health", "infrastructure", "wash"],
    },
    # ── ECONOMY (extended) ─────────────────────────────────────────────────────
    {
        "id": "gini",
        "name": "Gini Coefficient",
        "category": "Economy",
        "source": "wdi",
        "indicator": "SI.POV.GINI",
        "unit": "index (0–100)",
        "tags": ["gini", "inequality", "income distribution", "poverty", "equity", "lorenz"],
    },
    {
        "id": "poverty_365",
        "name": "Poverty Rate ($3.65/day)",
        "category": "Economy",
        "source": "wdi",
        "indicator": "SI.POV.LMIC",
        "unit": "% of population",
        "tags": ["poverty", "income", "lower middle class", "3.65", "dollar"],
    },
    {
        "id": "poverty_685",
        "name": "Poverty Rate ($6.85/day)",
        "category": "Economy",
        "source": "wdi",
        "indicator": "SI.POV.UMIC",
        "unit": "% of population",
        "tags": ["poverty", "income", "upper middle class", "6.85", "dollar"],
    },
    {
        "id": "trade_gdp",
        "name": "Trade Openness (% of GDP)",
        "category": "Economy",
        "source": "wdi",
        "indicator": "NE.TRD.GNFS.ZS",
        "unit": "% of GDP",
        "tags": ["trade", "openness", "exports", "imports", "gdp", "globalization"],
    },
    {
        "id": "exports_gdp",
        "name": "Exports of Goods & Services (% of GDP)",
        "category": "Economy",
        "source": "wdi",
        "indicator": "NE.EXP.GNFS.ZS",
        "unit": "% of GDP",
        "tags": ["exports", "trade", "goods", "services", "gdp", "openness"],
    },
    {
        "id": "tax_revenue",
        "name": "Tax Revenue (% of GDP)",
        "category": "Economy",
        "source": "wdi",
        "indicator": "GC.TAX.TOTL.GD.ZS",
        "unit": "% of GDP",
        "tags": ["tax", "revenue", "fiscal", "government", "gdp", "budget"],
    },
    {
        "id": "military_spending",
        "name": "Military Expenditure (% of GDP)",
        "category": "Economy",
        "source": "wdi",
        "indicator": "MS.MIL.XPND.GD.ZS",
        "unit": "% of GDP",
        "tags": ["military", "defense", "spending", "gdp", "arms", "security"],
    },
    {
        "id": "rd_expenditure",
        "name": "R&D Expenditure (% of GDP)",
        "category": "Economy",
        "source": "wdi",
        "indicator": "GB.XPD.RSDV.GD.ZS",
        "unit": "% of GDP",
        "tags": ["r&d", "research", "development", "innovation", "gdp", "science"],
    },
    {
        "id": "remittances",
        "name": "Personal Remittances Received (% of GDP)",
        "category": "Economy",
        "source": "wdi",
        "indicator": "BX.TRF.PWKR.DT.GD.ZS",
        "unit": "% of GDP",
        "tags": ["remittances", "migration", "transfers", "diaspora", "gdp", "income"],
    },
    {
        "id": "gross_savings",
        "name": "Gross Savings Rate",
        "category": "Economy",
        "source": "wdi",
        "indicator": "NY.GNS.ICTR.ZS",
        "unit": "% of GNI",
        "tags": ["savings", "investment", "capital", "gni", "economy", "accumulation"],
    },
    {
        "id": "gdp_per_capita_current",
        "name": "GDP per Capita (current USD)",
        "category": "Economy",
        "source": "wdi",
        "indicator": "NY.GDP.PCAP.CD",
        "unit": "current USD",
        "tags": ["gdp", "income", "wealth", "per capita", "dollar", "economy"],
    },
    {
        "id": "current_account",
        "name": "Current Account Balance (% of GDP)",
        "category": "Economy",
        "source": "wdi",
        "indicator": "BN.CAB.XOKA.GD.ZS",
        "unit": "% of GDP",
        "tags": ["current account", "balance of payments", "trade", "gdp", "surplus", "deficit"],
    },
    # ── HEALTH (extended) ──────────────────────────────────────────────────────
    {
        "id": "sanitation",
        "name": "Access to Basic Sanitation",
        "category": "Health",
        "source": "wdi",
        "indicator": "SH.STA.SMSS.ZS",
        "unit": "% of population",
        "tags": ["sanitation", "toilets", "hygiene", "wash", "health", "infrastructure"],
    },
    {
        "id": "hiv_prevalence",
        "name": "HIV Prevalence (ages 15–49)",
        "category": "Health",
        "source": "wdi",
        "indicator": "SH.DYN.AIDS.ZS",
        "unit": "% of population aged 15–49",
        "tags": ["hiv", "aids", "disease", "health", "epidemic", "prevalence"],
    },
    {
        "id": "hospital_beds",
        "name": "Hospital Beds (per 1,000 people)",
        "category": "Health",
        "source": "wdi",
        "indicator": "SH.MED.BEDS.ZS",
        "unit": "per 1,000 people",
        "tags": ["hospital", "beds", "health system", "infrastructure", "healthcare capacity"],
    },
    {
        "id": "physicians",
        "name": "Physicians (per 1,000 people)",
        "category": "Health",
        "source": "wdi",
        "indicator": "SH.MED.PHYS.ZS",
        "unit": "per 1,000 people",
        "tags": ["doctors", "physicians", "health workers", "healthcare", "medical"],
    },
    # ── EDUCATION (extended) ──────────────────────────────────────────────────
    {
        "id": "school_enrollment_tertiary",
        "name": "Tertiary School Enrollment",
        "category": "Education",
        "source": "wdi",
        "indicator": "SE.TER.ENRR",
        "unit": "% gross",
        "tags": ["education", "university", "tertiary", "higher education", "enrollment", "college"],
    },
    {
        "id": "youth_literacy",
        "name": "Youth Literacy Rate (ages 15–24)",
        "category": "Education",
        "source": "wdi",
        "indicator": "SE.ADT.1524.LT.ZS",
        "unit": "% of youth aged 15–24",
        "tags": ["literacy", "youth", "education", "reading", "young people"],
    },
    {
        "id": "school_enrollment_female_primary",
        "name": "Primary Enrollment — Girls",
        "category": "Education",
        "source": "wdi",
        "indicator": "SE.PRM.ENRR.FE",
        "unit": "% gross",
        "tags": ["education", "girls", "gender", "primary", "enrollment", "women"],
    },
    # ── ENVIRONMENT (extended) ────────────────────────────────────────────────
    {
        "id": "pm25_pollution",
        "name": "PM2.5 Air Pollution",
        "category": "Environment",
        "source": "wdi",
        "indicator": "EN.ATM.PM25.MC.M3",
        "unit": "micrograms per cubic meter",
        "tags": ["air pollution", "pm2.5", "particulate matter", "health", "environment", "smog"],
    },
    {
        "id": "agricultural_land",
        "name": "Agricultural Land (% of Land Area)",
        "category": "Environment",
        "source": "wdi",
        "indicator": "AG.LND.AGRI.ZS",
        "unit": "% of land area",
        "tags": ["agriculture", "land use", "farming", "crops", "food", "environment"],
    },
    {
        "id": "ghg_per_capita",
        "name": "Total GHG Emissions per Capita",
        "category": "Environment",
        "source": "wdi",
        "indicator": "EN.GHG.ALL.PC.CE.AR5",
        "unit": "metric tons CO₂-equivalent per capita",
        "tags": ["ghg", "greenhouse gas", "climate", "emissions", "carbon", "co2", "methane"],
    },
    {
        "id": "energy_use",
        "name": "Energy Use per Capita",
        "category": "Environment",
        "source": "wdi",
        "indicator": "EG.USE.PCAP.KG.OE",
        "unit": "kg of oil equivalent per capita",
        "tags": ["energy", "consumption", "fossil fuel", "per capita", "electricity"],
    },
    {
        "id": "freshwater_withdrawal",
        "name": "Freshwater Withdrawal (% of Resources)",
        "category": "Environment",
        "source": "wdi",
        "indicator": "ER.H2O.FWTL.ZS",
        "unit": "% of internal resources",
        "tags": ["water", "freshwater", "resource", "withdrawal", "scarcity", "drought"],
    },
    # ── DEMOGRAPHICS (extended) ────────────────────────────────────────────────
    {
        "id": "population_density",
        "name": "Population Density",
        "category": "Demographics",
        "source": "wdi",
        "indicator": "EN.POP.DNST",
        "unit": "people per sq. km of land area",
        "tags": ["population", "density", "crowding", "land", "demographics"],
    },
    {
        "id": "age_dependency",
        "name": "Age Dependency Ratio",
        "category": "Demographics",
        "source": "wdi",
        "indicator": "SP.POP.DPND",
        "unit": "% of working-age population",
        "tags": ["dependency", "aging", "demographics", "elderly", "youth", "working age"],
    },
    {
        "id": "net_migration",
        "name": "Net Migration",
        "category": "Demographics",
        "source": "wdi",
        "indicator": "SM.POP.NETM",
        "unit": "number of people (5-year period)",
        "tags": ["migration", "immigration", "emigration", "refugees", "diaspora", "demographics"],
    },
    {
        "id": "population_growth",
        "name": "Population Growth Rate",
        "category": "Demographics",
        "source": "wdi",
        "indicator": "SP.POP.GROW",
        "unit": "% per year",
        "tags": ["population", "growth", "demographics", "rate", "increase"],
    },
    # ── GOVERNANCE (extended) ──────────────────────────────────────────────────
    {
        "id": "control_corruption",
        "name": "Control of Corruption (WGI)",
        "category": "Governance",
        "source": "wdi",
        "indicator": "CC.EST",
        "unit": "estimate (–2.5 to +2.5)",
        "tags": ["corruption", "governance", "institutions", "wgi", "transparency", "rule of law"],
    },
    {
        "id": "political_stability",
        "name": "Political Stability (WGI)",
        "category": "Governance",
        "source": "wdi",
        "indicator": "PV.EST",
        "unit": "estimate (–2.5 to +2.5)",
        "tags": ["political stability", "violence", "conflict", "governance", "wgi", "security"],
    },
    {
        "id": "rule_of_law",
        "name": "Rule of Law (WGI)",
        "category": "Governance",
        "source": "wdi",
        "indicator": "RL.EST",
        "unit": "estimate (–2.5 to +2.5)",
        "tags": ["rule of law", "justice", "institutions", "governance", "wgi", "legal"],
    },
    {
        "id": "govt_effectiveness",
        "name": "Government Effectiveness (WGI)",
        "category": "Governance",
        "source": "wdi",
        "indicator": "GE.EST",
        "unit": "estimate (–2.5 to +2.5)",
        "tags": ["government", "effectiveness", "public services", "governance", "wgi", "institutions"],
    },
    {
        "id": "voice_accountability",
        "name": "Voice & Accountability (WGI)",
        "category": "Governance",
        "source": "wdi",
        "indicator": "VA.EST",
        "unit": "estimate (–2.5 to +2.5)",
        "tags": ["democracy", "accountability", "voice", "governance", "wgi", "civil society", "press freedom"],
    },
    {
        "id": "press_freedom",
        "name": "Freedom of the Press Index",
        "category": "Governance",
        "source": "wdi",
        "indicator": "IQ.CPA.IRAI.XQ",
        "unit": "CPIA rating (1–6)",
        "tags": ["press freedom", "media", "governance", "democracy", "accountability"],
    },
]

CATEGORIES = sorted(set(ind["category"] for ind in INDICATORS))
