"""
Curated catalog of development indicators from OWID and World Bank (WDI).
Each entry defines source, fetch parameters, unit, and search tags.
"""

INDICATORS = [
    # ── HEALTH ────────────────────────────────────────────────────────────────
    {
        "id": "under5_mortality",
        "name": "Under-5 Mortality Rate",
        "category": "Health",
        "source": "owid",
        "slug": "child-mortality",
        "unit": "deaths per 1,000 live births",
        "tags": ["health", "mortality", "children", "death", "child", "under 5"],
    },
    {
        "id": "life_expectancy",
        "name": "Life Expectancy at Birth",
        "category": "Health",
        "source": "owid",
        "slug": "life-expectancy",
        "unit": "years",
        "tags": ["health", "life", "expectancy", "longevity", "age"],
    },
    {
        "id": "maternal_mortality",
        "name": "Maternal Mortality Ratio",
        "category": "Health",
        "source": "owid",
        "slug": "maternal-mortality",
        "unit": "deaths per 100,000 live births",
        "tags": ["health", "maternal", "women", "mortality", "birth", "mothers"],
    },
    {
        "id": "infant_mortality",
        "name": "Infant Mortality Rate",
        "category": "Health",
        "source": "wdi",
        "indicator": "SP.DYN.IMRT.IN",
        "unit": "per 1,000 live births",
        "tags": ["health", "infant", "mortality", "baby", "child", "neonatal"],
    },
    {
        "id": "health_expenditure",
        "name": "Health Expenditure (% of GDP)",
        "category": "Health",
        "source": "wdi",
        "indicator": "SH.XPD.CHEX.GD.ZS",
        "unit": "% of GDP",
        "tags": ["health", "spending", "expenditure", "gdp", "budget"],
    },
    {
        "id": "malnutrition",
        "name": "Malnutrition Prevalence (children under 5)",
        "category": "Health",
        "source": "wdi",
        "indicator": "SH.STA.MALN.ZS",
        "unit": "% of children under 5",
        "tags": ["malnutrition", "nutrition", "hunger", "food", "children", "wasting"],
    },
    # ── ECONOMY ───────────────────────────────────────────────────────────────
    {
        "id": "gdp_per_capita_ppp",
        "name": "GDP per Capita, PPP (constant 2017 USD)",
        "category": "Economy",
        "source": "wdi",
        "indicator": "NY.GDP.PCAP.PP.KD",
        "unit": "constant 2017 USD",
        "tags": ["economy", "gdp", "income", "wealth", "ppp", "purchasing power"],
    },
    {
        "id": "gdp_growth",
        "name": "GDP Growth Rate",
        "category": "Economy",
        "source": "wdi",
        "indicator": "NY.GDP.MKTP.KD.ZG",
        "unit": "% per year",
        "tags": ["economy", "gdp", "growth", "rate", "recession"],
    },
    {
        "id": "extreme_poverty",
        "name": "Extreme Poverty Rate ($2.15/day)",
        "category": "Economy",
        "source": "owid",
        "slug": "share-of-population-in-extreme-poverty",
        "unit": "% of population",
        "tags": ["poverty", "extreme poverty", "income", "poor", "2.15", "dollar"],
    },
    {
        "id": "inflation",
        "name": "Inflation, Consumer Prices",
        "category": "Economy",
        "source": "wdi",
        "indicator": "FP.CPI.TOTL.ZG",
        "unit": "% per year",
        "tags": ["inflation", "prices", "cpi", "monetary", "economy"],
    },
    {
        "id": "unemployment",
        "name": "Unemployment Rate",
        "category": "Economy",
        "source": "wdi",
        "indicator": "SL.UEM.TOTL.ZS",
        "unit": "% of labor force",
        "tags": ["unemployment", "jobs", "labor", "work", "employment"],
    },
    {
        "id": "fdi",
        "name": "FDI Net Inflows (% of GDP)",
        "category": "Economy",
        "source": "wdi",
        "indicator": "BX.KLT.DINV.WD.GD.ZS",
        "unit": "% of GDP",
        "tags": ["fdi", "foreign direct investment", "investment", "trade", "capital"],
    },
    {
        "id": "oda",
        "name": "Net ODA Received (% of GNI)",
        "category": "Economy",
        "source": "wdi",
        "indicator": "DT.ODA.ODAT.GN.ZS",
        "unit": "% of GNI",
        "tags": ["oda", "aid", "development aid", "official development assistance", "donor"],
    },
    {
        "id": "govt_debt",
        "name": "Government Debt (% of GDP)",
        "category": "Economy",
        "source": "wdi",
        "indicator": "GC.DOD.TOTL.GD.ZS",
        "unit": "% of GDP",
        "tags": ["debt", "government", "fiscal", "budget", "gdp", "deficit"],
    },
    # ── EDUCATION ─────────────────────────────────────────────────────────────
    {
        "id": "literacy_rate",
        "name": "Adult Literacy Rate",
        "category": "Education",
        "source": "wdi",
        "indicator": "SE.ADT.LITR.ZS",
        "unit": "% of adults (15+)",
        "tags": ["education", "literacy", "reading", "writing", "adults", "school"],
    },
    {
        "id": "school_enrollment_primary",
        "name": "Primary School Enrollment",
        "category": "Education",
        "source": "wdi",
        "indicator": "SE.PRM.ENRR",
        "unit": "% gross",
        "tags": ["education", "school", "enrollment", "primary", "children"],
    },
    {
        "id": "school_enrollment_secondary",
        "name": "Secondary School Enrollment",
        "category": "Education",
        "source": "wdi",
        "indicator": "SE.SEC.ENRR",
        "unit": "% gross",
        "tags": ["education", "school", "enrollment", "secondary"],
    },
    {
        "id": "edu_expenditure",
        "name": "Education Expenditure (% of GDP)",
        "category": "Education",
        "source": "wdi",
        "indicator": "SE.XPD.TOTL.GD.ZS",
        "unit": "% of GDP",
        "tags": ["education", "spending", "expenditure", "gdp", "budget"],
    },
    # ── ENVIRONMENT ───────────────────────────────────────────────────────────
    {
        "id": "co2_per_capita",
        "name": "CO₂ Emissions per Capita",
        "category": "Environment",
        "source": "owid",
        "slug": "co-emissions-per-capita",
        "unit": "tonnes per person",
        "tags": ["co2", "carbon", "emissions", "climate", "environment", "pollution", "ghg"],
    },
    {
        "id": "forest_area",
        "name": "Forest Area (% of Land)",
        "category": "Environment",
        "source": "wdi",
        "indicator": "AG.LND.FRST.ZS",
        "unit": "% of land area",
        "tags": ["forest", "trees", "land", "environment", "deforestation", "nature"],
    },
    {
        "id": "access_electricity",
        "name": "Access to Electricity",
        "category": "Environment",
        "source": "owid",
        "slug": "share-of-the-population-with-access-to-electricity",
        "unit": "% of population",
        "tags": ["electricity", "energy", "access", "infrastructure", "power"],
    },
    {
        "id": "renewable_energy",
        "name": "Renewable Energy Share",
        "category": "Environment",
        "source": "wdi",
        "indicator": "EG.FEC.RNEW.ZS",
        "unit": "% of total final energy",
        "tags": ["renewable", "energy", "solar", "wind", "environment", "climate", "clean"],
    },
    # ── DEMOGRAPHICS ──────────────────────────────────────────────────────────
    {
        "id": "population",
        "name": "Total Population",
        "category": "Demographics",
        "source": "wdi",
        "indicator": "SP.POP.TOTL",
        "unit": "number of people",
        "tags": ["population", "people", "demographics", "size", "headcount"],
    },
    {
        "id": "fertility_rate",
        "name": "Total Fertility Rate",
        "category": "Demographics",
        "source": "wdi",
        "indicator": "SP.DYN.TFRT.IN",
        "unit": "births per woman",
        "tags": ["fertility", "birth rate", "children", "demographics", "reproduction"],
    },
    {
        "id": "urban_population",
        "name": "Urban Population Share",
        "category": "Demographics",
        "source": "wdi",
        "indicator": "SP.URB.TOTL.IN.ZS",
        "unit": "% of total population",
        "tags": ["urban", "city", "urbanization", "demographics", "rural"],
    },
    # ── GOVERNANCE ────────────────────────────────────────────────────────────
    {
        "id": "women_parliament",
        "name": "Women in Parliament",
        "category": "Governance",
        "source": "owid",
        "slug": "seats-held-by-women-in-national-parliaments",
        "unit": "% of parliamentary seats",
        "tags": ["women", "parliament", "gender", "politics", "governance", "representation"],
    },
    {
        "id": "access_water",
        "name": "Access to Safe Drinking Water",
        "category": "Health",
        "source": "wdi",
        "indicator": "SH.H2O.SMDW.ZS",
        "unit": "% of population",
        "tags": ["water", "sanitation", "access", "health", "infrastructure", "wash"],
    },
]

CATEGORIES = sorted(set(ind["category"] for ind in INDICATORS))
